server:
  port: 8082
    #ssl:
    # key-store: classpath:7639158_baidu_com.pfx
    # key-store-type: PKCS12
  # key-store-password: ADADAS1

  servlet:
    context-path: /zycm-advert-publish

  tomcat:
    uri-encoding: UTF-8
    threads:
      min-spare: 50
      max: 1000

# 日志配置
logging:
  level:
    com.zycm.zybao: debug
    org.springframework: warn
    com.zycm.zybao.amq: warn
    com.zycm.zybao.service.task: warn
    com.zycm.zybao.web.websocket: warn
    net.sf.json: error
    com.zycm.zybao.dao: warn

spring:
  application:
    name: zycm-advert-publish
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  # 文件上传
  servlet:
    uploadTempDir: /home/docker_xf/ftp/temp/
    multipart:
      # 单个文件大小
      max-file-size:  -1
      # 设置总上传的文件大小
      max-request-size:  -1

  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: false
  # Redis
  redis:
    # 地址
    host: 192.168.2.169
    # 端口，默认为6379
    port: 6579
    # 数据库索引
    database: 1
    # 密码
    password: redis1234
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

  #druid
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://192.168.2.169:3406/zycm_advert_publish?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: mysql1234
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: admin
        login-password: 666666
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.zycm.zybao.model
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/*.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: login.html
    # 权限认证失败地址
    unauthorizedUrl: noPerms.html
    # 首页地址
    indexUrl: index.html
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  filterChainDefinitionMap:
    /css/**: anon
    /images/**: anon
    /js/**: anon
    /common/**: anon
    /layui/**: anon
    /mod/**: anon
    /ckplayer/**: anon
    /ffpeg/**: anon
    /json/**: anon
    /srsplayer/**: anon
    /srs_player/**: anon
    /mediaAttribute/selectMediaProgram: anon # 获取终端档期数据     给选点系统调用
    /memberOrders/syncCustomerOrders: anon # 同步订单数据  选点系统
    /sysUser/backLogin: anon
    /module/selectUserPermission: anon
    /aliyun/getsts: anon
    /error1/**: anon
    /front/page/**: anon
    /webservice/**: anon
    /wx/**: anon
    /front/login: anon
    /**: authc,userlog


# ftp相关配置
sys:
  #系统版本
  version: 4.0.0
  scode: "dadjalsjdsaj21mnjbn13nl1n3n12nl1n3"
  ftp:
    # 模式支持 oss和本地 ftp两种模式(需要搭建ftp服务)
    model: ftp
    #系统发布模式设置  batch分批发布即延时发布(不支持)  realtime实时发布无延迟
  publish:
    model: realtime
  material:
    #内容审核 0人工审核 1预先智能审核(阿里的智能审核)
    audit: 0
  #redis存值的关联字符
  prefix: yanshi_

ftp:
  ip: 192.168.2.169
  username: cs
  password: cs1234
  port: 2222
  encode: UTF-8
  connectMode: PASV
  server:
    path: ftp://192.168.2.169:2222
  master:
    getmaterialmd5: http://192.168.2.169:9081/advert-ftpserver-service/check/getMaterialMD5
img:
  server:
    path: http://demo.zycmjs.com:9081
    screenshot:
      expression: http://*
oss:
  endpoint: https://xxx.xxx.com
  accessKeyId: xxxxxxx
  accessKeySecret: xxxxxxx
  bucketName: xxxxxx
  # oss资源预览前缀
  preview: https://xxxxx.xxx.com
  #OSS鉴权服务接口 媒体终端获取oss临时授权用
  ossStsServer: http://osssts.xxx.com:8082/zycm-advert-publish/aliyun/getsts

#oss临时授权
aliyun:
  regionId: cn-shenzhen
  accessKeyId: xxxxxxxxx
  secret: xxxxxxxxxxxxxxxxxxx
  #举例 acs:ram::221312312312:role/aliyunosstoken
  roleArn: xxxxxx
  #自定义
  roleSessionName: xxxxxxxx

#智能内容审核
aicheck:
  regionId: cn-shenzhen
  #节点访问的域名
  endPointName: xxxx.com

# MQ配置
mq:
  receiver_top: zhibo_respose_cs_PTP
  sender_top: zhibo_request_cs_PTP
  brokerURL: failover:(nio+ssl://192.168.2.169:61616)
  userName: zhangsan
  password: 123
  receiverServiceClientId: service_receiver
  senderServiceClientId: service_sender
  certificate:
    certificateName: classpath:key.p12
    certificatePwd: yanshi@2023

  # mq的自带管理后端
  web:
    userName: cs
    password: cs12343
  # mq自带的api 发布时改成127.0.0.1
  api:
    url: http://192.168.2.169:8162/api/jolokia
    J4pReadRequest: org.apache.activemq:type=Broker,brokerName=localhost,destinationType=Topic,destinationName=zhibo_request_cs_PTP


# 物联卡配置
# 电信物联卡
telecom:
  iot:
    https:
      prefix: http://api.ct10649.com:9001/m2m_ec/query.do
    user_id: xxxxxxxxxxxxxxxxxxxxxx
    passWord: xxxxxxxxxxxxxxxxxxxxxxxxxxx
    key: xxxxxxxxxxxxx
# 联通物联卡 账户密码可2个一样
unicom:
  iot:
    https:
      prefix: https://api.10646.cn/rws/api/v1/
    username: xxxxxxxxx
    secretkey: xxxxxxxxxxxxxxxxxxxxxxxxxxx
    username2: xxxxxxxxxxxxxxx
    secretkey2: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
    url:
      #获取卡信息接口
      ctdUsages: https://api.10646.cn/rws/api/v1/devices/{iccid}/ctdUsages
# 移动物联卡
mobile:
  iot:
    https:
      prefix: http://120.78.169.220:8089/api/Service/
    username: xxxxxx
    key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# 公众号预警通知配置信息
wx:
  warn:
    notice:
      mpId: xxxxxxxxxxxxx
      appId: xxxxxxxxxxxxxxxxxxxxxx
      appSecret: xxxxxxxxxxxxxxxxxxxxxxxxxx
      token: xxxxxxxxxxxxxxxxxxxxxxxxx
      templateId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      #回调地址
      url: http://192.168.2.234:8080/login
# 设备离线推送参数配置
task:
  enabled: true
  notice:
    #统计离线频率的时间差值，单位为分钟
    timedff: 30
    #需延迟推送的频率值
    frequency: 10
    #推送的时间范围
    starttime: "07:00:00"
    etime: "23:00:00"
  poolSize: 10

# 流媒体服务相关配置
live:
  remotePreview:
    protocol: rtmp
    ip: 192.168.2.169
    port: 1935
    appName: remotelive
    #分享地址
    shareAddr: http://xxxxxx.com:8081/video.html
    http:
      port: 8080
  default:
    preview:
      pic:
        #默认封面图地址
        addr: http://xxxx.xxxx.com/lun2.png
srs:
  api:
    #获取流信息列表
    getStream: http://192.168.2.169:1985/api/v1/streams
    #获取设备列表
    getClient: http://192.168.2.169:1985/api/v1/clients?start=0&count=1000
